plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/julietteckaraman/Desktop/feelfullyyou-site"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/for-her"
to = "/for-her.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/for-him"
to = "/for-him.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/men"
to = "/for-him.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/for-both"
to = "/for-both.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/cards"
to = "/cards.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/work-with-me"
to = "/work-with-me.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-beginning"
to = "/the-beginning.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/couples-intensive"
to = "/couples-intensive.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/womens-intensive"
to = "/womens-intensive.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/womens-six-week-intensive"
to = "/womens-six-week-intensive.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/mens-intensive"
to = "/mens-intensive.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/mens-six-week-intensive"
to = "/mens-six-week-intensive.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-unspoken-distance"
to = "/the-unspoken-distance.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/10-touch-rituals"
to = "/10-touch-rituals.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/31-daily-touch-points"
to = "/31-daily-touch-points.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/touch-point"
to = "/touch-point.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/touch-point-live"
to = "/touch-point-live.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/7-days-scrumptiousness"
to = "/7-days-scrumptiousness.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sacred-no"
to = "/sacred-no.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/communication-reboot-kit"
to = "/communication-reboot-kit.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/romantic-relationship-repair-kit"
to = "/romantic-relationship-repair-kit.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/between-touches"
to = "/between-touches.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/when-she-goes-quiet"
to = "/when-she-goes-quiet.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/shop"
to = "/shop.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/media-and-pr"
to = "/media-and-pr.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/free-resources"
to = "/free-resources.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/grief-duality-process"
to = "/grief-duality-process.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/getintouch"
to = "/contact.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-scrumptious-and-pleasure-candles"
to = "/the-scrumptious-and-pleasure-candles.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-scrumptious--and-pleasure-candles"
to = "/the-scrumptious-and-pleasure-candles.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/landing"
to = "/landing.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/trip-wire"
to = "/trip-wire.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/trip"
to = "/trip-wire.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-10rituals"
to = "/thankyou-10rituals.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-31touchpoints"
to = "/thankyou-31touchpoints.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-both"
to = "/thankyou-both.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-between-touches"
to = "/thankyou-between-touches.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-between-touches-only"
to = "/thankyou-between-touches-only.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-when-she-goes-quiet"
to = "/thankyou-when-she-goes-quiet.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-when-she-goes-quiet-only"
to = "/thankyou-when-she-goes-quiet-only.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/touch-point-thankyou"
to = "/touch-point-thankyou.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/tb-thank-you-page"
to = "/tb-thank-you-page.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/success-between-touches"
to = "/success-between-touches.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/payment"
to = "https://shop.feelfullyyou.com/payment"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/payment-4108"
to = "https://shop.feelfullyyou.com/payment-4108"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/payment-2838"
to = "https://shop.feelfullyyou.com/payment-2838"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/payment-6weeks"
to = "https://shop.feelfullyyou.com/payment-6weeks"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/payment-6weeks-5194"
to = "https://shop.feelfullyyou.com/payment-6weeks-5194"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/7-day-no-challenge"
to = "https://shop.feelfullyyou.com/7-day-no-challenge"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-romantic-relationship-repair-kit-177535"
to = "https://shop.feelfullyyou.com/the-romantic-relationship-repair-kit-177535"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/couples-intensive785342"
to = "https://shop.feelfullyyou.com/couples-intensive785342"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/mens-intensive-3894"
to = "https://shop.feelfullyyou.com/mens-intensive-3894"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-touch-reboot-kit-payment-9978"
to = "https://shop.feelfullyyou.com/the-touch-reboot-kit-payment-9978"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/when-she-has-gone-quiet-guide-234440"
to = "https://shop.feelfullyyou.com/when-she-has-gone-quiet-guide-234440"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/between-touches-checkout"
to = "https://shop.feelfullyyou.com/between-touches"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/telegram-support"
to = "https://shop.feelfullyyou.com/telegram-support"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/touch-base-anchor"
to = "/touch-base-anchor.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/2-order-form-8223"
to = "https://shop.feelfullyyou.com/2-order-form-8223"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/beliefs-journal"
to = "https://shop.feelfullyyou.com/beliefs-journal"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-communication-kit-order-page"
to = "https://shop.feelfullyyou.com/the-communication-kit-order-page"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/links"
to = "/links.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/connect-with-essence"
to = "/connect-with-essence.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-room"
to = "/the-room.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thankyou-grief"
to = "/thankyou-grief.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/be-touched"
to = "https://findthetouch.live/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "https://shop.feelfullyyou.com/terms"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/404.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]